=== Khmelov/JD2018-08-21/src/by/it/kisielev/jd02_07/Books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://kisielev.it.by/"
        xmlns:tns="http://kisielev.it.by/"
        elementFormDefault="qualified">

 <element name="Books">
     <complexType>
         <sequence>
             <element name="Book"
                      type="tns:Book"
                      minOccurs="0"
                      maxOccurs="unbounded">
             </element>
         </sequence>
     </complexType>
 </element>

    <complexType name="Book">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Genres" type="string"/>
            <element name="Assessment" type="string"/>
            <element name="Comments" type="tns:Comment"/>
        </sequence>
    </complexType>

    <complexType name="Comments">
        <sequence>
            <element
                name="Comment"
                type="tns:Comment"
                minOccurs="0"
                maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Comment">
        <sequence>
            <element name="NameBook" type="string"/>
            <element name="AssessmentBook" type="positiveInteger"/>
            <element name="Ð¡ommentBook" type="string"/>
        </sequence>
    </complexType>
</schema>

=== Khmelov/JD2018-08-21/src/by/it/kisielev/jd02_07/BooksXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://kisielev.it.by/"
       xsi:schemaLocation="http://kisielev.it.by/ Books.xsd"
>
    <Book>
        <Name>Золушка</Name>
        <Genres>Сказака</Genres>
        <Assessment>9/10</Assessment>
        <Comments>
            <Comment>
                <NameBook>Золушка</NameBook>
                <AssessmentBook>9</AssessmentBook>
                <СommentBook>Достойная книга для малышей.</СommentBook>
            </Comment>
            <Comment>
                <NameBook>Золушка</NameBook>
                <AssessmentBook>10</AssessmentBook>
                <СommentBook>Дочка в восторге от этой книги! Автор огонь.</СommentBook>
            </Comment>
        </Comments>
    </Book>
    <Book>
        <Name>Гарри Поттре 7: Дары смерти</Name>
        <Genres>фантастика, Приключения, Драмма</Genres>
        <Assessment>10/10</Assessment>
        <Comments>
            <Comment>
                <NameBook>Гарри Поттре 7: Дары смерти</NameBook>
                <AssessmentBook>4</AssessmentBook>
                <СommentBook>Фильм оказался не так хорошь чем все предыдущие части,скатились.</СommentBook>
            </Comment>
        </Comments>
    </Book>
</Books>
