=== Khmelov/JD2018-08-21/src/by/it/kisielev/jd02_07/Books.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT Books (Book)+>
        <!ELEMENT Book (Name, Genres, Assessment, Comments)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Genres (#PCDATA)>
        <!ELEMENT Assessment (#PCDATA)>
        <!ELEMENT Comments (Comment)+>
        <!ELEMENT Comment (NameBook, AssessmentBook, СommentBook)>
        <!ELEMENT NameBook (#PCDATA)>
        <!ELEMENT AssessmentBook (#PCDATA)>
        <!ELEMENT СommentBook (#PCDATA)>

=== Khmelov/JD2018-08-21/src/by/it/kisielev/jd02_07/BooksDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Persons SYSTEM "Books.dtd">
<Books>
    <Book>
        <Name>Золушка</Name>
        <Genres>Сказака</Genres>
        <Assessment>9/10</Assessment>
        <Comments>
            <Comment>
                <NameBook>Золушка</NameBook>
                <AssessmentBook>9</AssessmentBook>
                <СommentBook>Достойная книга для малышей.</СommentBook>
            </Comment>
            <Comment>
                <NameBook>Золушка</NameBook>
                <AssessmentBook>10</AssessmentBook>
                <СommentBook>Дочка в восторге от этой книги! Автор огонь.</СommentBook>
            </Comment>
        </Comments>
    </Book>
    <Book>
        <Name>Гарри Поттре 7: Дары смерти</Name>
        <Genres>фантастика, Приключения, Драмма</Genres>
        <Assessment>10/10</Assessment>
        <Comments>
            <Comment>
                <NameBook>Гарри Поттре 7: Дары смерти</NameBook>
                <AssessmentBook>4</AssessmentBook>
                <СommentBook>Фильм оказался не так хорошь чем все предыдущие части,скатились.</СommentBook>
            </Comment>
        </Comments>
    </Book>
</Books>
