=== Khmelov/JD2018-08-21/src/by/it/kisielev/jd02_09/Persons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://bean.jd02_09.kisielev.it.by/"
        xmlns:tns="http://bean.jd02_09.kisielev.it.by/"
        elementFormDefault="qualified">

 <element name="Persons">
     <complexType>
         <sequence>
             <element name="Person"
                      type="tns:Person"
                      minOccurs="1"
                      maxOccurs="unbounded">
             </element>
         </sequence>
     </complexType>
 </element>

    <complexType name="Person">
        <sequence>
            <element name="Email" type="string"/>
            <element name="Nickname" type="string"/>
            <element name="Password" type="string"/>
            <element name="Ads" type="tns:Ads"/>
        </sequence>
    </complexType>

    <complexType name="Ads">
        <sequence>
            <element
                name="Ad"
                type="tns:Ad"
                minOccurs="1"
                maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="Ad">
        <sequence>
            <element name="Description" type="string"/>
            <element name="Adreses" type="string"/>
            <element name="Floor" type="positiveInteger"/>
            <element name="Floors" type="positiveInteger"/>
            <element name="Square" type="float"/>
            <element name="Price" type="float"/>
        </sequence>
        <attribute name="Rooms" type="positiveInteger" use="required"/>
    </complexType>
</schema>

=== Khmelov/JD2018-08-21/src/by/it/kisielev/jd02_09/PersonsXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://bean.jd02_09.kisielev.it.by/"
         xsi:schemaLocation="http://bean.jd02_09.kisielev.it.by/ Persons.xsd"
>
    <Persons>
        <Persone>
            <Email>asdasd@gmail.com</Email>
            <Nickname>asdasd</Nickname>
            <Password>asdasd123123</Password>
            <Ads>
                <Ad Rooms="2">
                    <Descriptions> Квартира  в центре города</Descriptions>
                    <Adreses>пр.Независимости, д. 33 кв.25</Adreses>
                    <Floor>2</Floor>
                    <Floors>5</Floors>
                    <Square>60</Square>
                    <Price>66666</Price>
                </Ad>
                <Ad Rooms="1">
                    <Descriptions> Квартира  в центре города</Descriptions>
                    <Adreses>пр.Зеленого, д. 78 кв.6</Adreses>
                    <Floor>2</Floor>
                    <Floors>5</Floors>
                    <Square>25</Square>
                    <Price>66666</Price>
                </Ad>
            </Ads>
        </Persone>
        <Persone>
            <Email>qwertyuiop@gmail.com</Email>
            <Nickname>T1T1T1T</Nickname>
            <Password>QWERTYUIOP</Password>
            <Ads>
                <Ad Rooms="3">
                    <Descriptions> Квартира  на окраине</Descriptions>
                    <Adreses>у.Тебя, д.2 кв.229</Adreses>
                    <Floor>19</Floor>
                    <Floors>6</Floors>
                    <Square>70</Square>
                    <Price>100009</Price>
                </Ad>
            </Ads>
        </Persone>
    </Persons>
